[2025-05-04 15:47:22,652] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-04 15:47:40,970] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2025-05-04 15:47:40,970] [INFO] [runner.py:605:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None /gscratch/stf/lbc800/mistral-KD/KD_HF.py
[2025-05-04 15:47:43,160] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-04 15:47:51,651] [INFO] [launch.py:139:main] 0 NCCL_VERSION=2.17.1-1
[2025-05-04 15:47:51,651] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2025-05-04 15:47:51,651] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2025-05-04 15:47:51,651] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2025-05-04 15:47:51,651] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2025-05-04 15:47:51,651] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2025-05-04 15:47:51,651] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2025-05-04 15:47:51,652] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2025-05-04 15:47:51,652] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=2, node_rank=0
[2025-05-04 15:47:51,652] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2025-05-04 15:47:51,652] [INFO] [launch.py:164:main] dist_world_size=2
[2025-05-04 15:47:51,652] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2025-05-04 15:47:51,683] [INFO] [launch.py:256:main] process 78789 spawned with command: ['/usr/bin/python3', '-u', '/gscratch/stf/lbc800/mistral-KD/KD_HF.py', '--local_rank=0']
[2025-05-04 15:47:51,696] [INFO] [launch.py:256:main] process 78790 spawned with command: ['/usr/bin/python3', '-u', '/gscratch/stf/lbc800/mistral-KD/KD_HF.py', '--local_rank=1']
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:20<01:00, 20.24s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:41<00:41, 20.97s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [01:03<00:21, 21.11s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:19<00:00, 19.13s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:19<00:00, 19.77s/it]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:20<00:20, 20.88s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00,  9.26s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:21<00:00, 11.00s/it]
[2025-05-04 15:49:54,384] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/usr/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
[2025-05-04 15:49:57,463] [INFO] [comm.py:669:init_distributed] cdb=None
[rank0]: Traceback (most recent call last):
[rank0]:   File "/gscratch/stf/lbc800/mistral-KD/KD_HF.py", line 90, in <module>
[rank0]:     trainer = KDTrainer(
[rank0]:   File "/gscratch/stf/lbc800/mistral-KD/KD_HF.py", line 18, in __init__
[rank0]:     super().__init__(**kwargs)
[rank0]:   File "/transformers/src/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank0]:     return func(*args, **kwargs)
[rank0]: TypeError: Trainer.__init__() got an unexpected keyword argument 'temperatue'
[rank0]:[W504 15:49:59.723356432 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2025-05-04 15:50:03,939] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 78789
[2025-05-04 15:50:04,060] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 78790
[2025-05-04 15:50:04,061] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python3', '-u', '/gscratch/stf/lbc800/mistral-KD/KD_HF.py', '--local_rank=1'] exits with return code = 1
